### ISSUE TITLE
 https://cn.tql.ink无法访问

### ISSUE THREAD

**Issue by LiuYiLin-CA** [kasuganosoras/cloudflare-worker-blog#11]
资源文件能否放在GitHub的仓库中调用？这样可以保证稳定性

**Comment by kasuganosoras** [comment]
此服务器已下线，可自行更换为其他大厂 CDN，例如 cdnjs，cloudflare 之类的
你也可以临时从 cdn.zerodream.net 下载对应资源，放到本地，不要长期使用，这个 CDN 随时可能下线
