### ISSUE TITLE
如何修改首页文章数量

### ISSUE THREAD

**Issue by dewjohn** [kasuganosoras/cloudflare-worker-blog#13]
默认显示5篇文章，如何修改成3篇文章呢

**Comment by kasuganosoras** [comment]
https://github.com/kasuganosoras/cloudflare-worker-blog/blob/master/workers-sakurafrp.js#L134
https://github.com/kasuganosoras/cloudflare-worker-blog/blob/master/workers-sakurafrp.js#L136
https://github.com/kasuganosoras/cloudflare-worker-blog/blob/master/workers-sakurafrp.js#L137
https://github.com/kasuganosoras/cloudflare-worker-blog/blob/master/workers-sakurafrp.js#L174

把 5 改成 3

**Comment by dewjohn** [comment]
感谢！
