### ISSUE TITLE
如何使用其它仓库

### ISSUE THREAD

**Issue by zxjzxj0010** [kasuganosoras/cloudflare-worker-blog#7]
想用别的仓库，可用raw（纯数据）方式访问md、list。请问一下该怎么改部署在cf的js脚本。

**Comment by ghost** [comment]
额, repo主提供的 js 第一行就是啊, 把那里改了就是

**Comment by kasuganosoras** [comment]
我假设问题已经解决，如果有其他问题可以回复打开 Issue
